language: ruby
cache: bundler

rvm:
  - 2.0.0

# Not sure why I need this!
before_install:
  - 'gem install bundler'

script: 'bundle exec rake'

notifications:
  email:
    recipients:
      - iamkcerb@gmail.com
    on_failure: change
    on_success: never
